# Generated by Django 5.0.2 on 2024-02-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_contact',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user_contact',
            old_name='PhoneNumber',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='user_contact',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user_contact',
            name='created',
        ),
    ]
